### ISSUE TITLE
[Request] Support for Disney Plus?

### ISSUE THREAD

**Issue by RuggMatt** [BRForgers/RichPresence-Addon#3]
Hello, 

This extension is exactly what I was looking for. I noticed there is support for a number of video streaming services. 

Any chance Disney+ could be added?

**Comment by Lulalaby** [comment]
Please!

**Comment by allanf181** [comment]
disney+ has not yet launched in my country, I can see that after the launch

**Comment by allanf181** [comment]
Done in 1.8
